accent = "#7c7ca8"
cursor = "#c8c8c8"
foreground = "#c8c8c8"
background = "#13131D"
selection_foreground = "#434353"
selection_background = "#13131D"

color0 = "#13131D"
color1 = "#EA90A8"
color2 = "#a6b2c7"
color3 = "#D18BA2"
color4 = "#7c7ca8"
color5 = "#9f859f"
color6 = "#919ab7"
color7 = "#a1a2a7"
color8 = "#434353"
color9 = "#f6bfce"
color10 = "#d1d9e4"
color11 = "#e3aebf"
color12 = "#bcbcd4"
color13 = "#bfadbf"
color14 = "#d2d7e3"
color15 = "#c8c8c8"
